In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("sales.csv")

In [4]:
df.head(4)

,transaction_id,customer_id,customer_name,email,purchase_date,product_id,category,price,quantity,total_amount,payment_method,delivery_status,customer_address
0,1001,102.0,Amy Wells,caroladams@gmail.com,24/01/2024,1023,Clothing,4210.71,-1,-4210.71,creditcard,Pending,"5769 Tracy Lane\nPort Amy, AZ 35865"
1,1002,435.0,Joshua Lopez,brownbenjamin,05/09/2023,1029,Electronics,3298.49,-3,-9895.47,Debit Card,Delivered,"70936 Rangel Falls\nWellshaven, AK 75186"
2,1003,348.0,Richard Alvarado,rose47@hotmail.com,09/07/2024,1078,Books,2387.86,6,14327.16,CC,Returned,"724 Aaron Villages\nPatriciachester, VA 64309"
3,1004,270.0,Nichole Nelson,sgibbs@reeves.org,28/07/2023,1090,Clothing,3780.65,2,7561.30,creditcard,Shipped,"4983 James Plains\nRoachland, NJ 41398"

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    1004 non-null   int64
 1   customer_id       1001 non-null   float64
 2   customer_name     951 non-null    str
 3   email             1004 non-null   str
 4   purchase_date     1004 non-null   str
 5   product_id        1004 non-null   int64
 6   category          837 non-null    str
 7   price             946 non-null    float64
 8   quantity          1004 non-null   int64
 9   total_amount      757 non-null    float64
 10  payment_method    866 non-null    str
 11  delivery_status   873 non-null    str
 12  customer_address  950 non-null    str
dtypes: float64(3), int64(3), str(7)
memory usage: 102.1 KB

In [44]:
df.describe()

,transaction_id,customer_id,product_id,price,quantity,total_amount
count,1004.0,1001.0,1004.0,946.0,1004.0,757.0
mean,1498.614542,251.337662,1050.570717,2512.791765,2.129482,6213.121281
std,289.787913,141.361692,28.617531,1436.064377,4.302746,14171.071717
min,1001.0,1.0,1001.0,12.92,-5.0,-43614.4
25%,1247.75,134.0,1025.0,1310.025,-1.0,-1774.66
50%,1498.5,248.0,1052.0,2531.045,2.0,3760.56
75%,1749.25,373.0,1076.0,3780.65,6.0,13484.96
max,2000.0,499.0,1099.0,4998.71,9.0,74608.32